#!/bin/bash

# Apply theme based on DTHEME setting # Run as target user, not root
sudo -u $TARGET_USER bash << EOF
if [ "$DTHEME" = "light" ]; then
    WALLPAPER="/usr/share/wallpapers/$D_WPP/contents/images/5120x2880.png"
else
    plasma-apply-desktoptheme breeze-dark >/dev/null 2>&1
    plasma-apply-colorscheme BreezeDark >/dev/null 2>&1
    kwriteconfig6 --file kdeglobals --group "General" --key "ColorScheme" "BreezeDark"
    kwriteconfig6 --file kdeglobals --group "KDE" --key "LookAndFeelPackage" "org.kde.breezedark.desktop"
    WALLPAPER="/usr/share/wallpapers/$D_WPP/contents/images_dark/5120x2880.png"
fi
kwriteconfig6 --file plasma-org.kde.plasma.desktop-appletsrc \
--group "Containments" --group "1" --group "Wallpaper" --group "org.kde.image" --group "General" \
--key "Image" "\$WALLPAPER"

## All this top part works fine.

# Taskbar tweaks
kwriteconfig6 --file plasmashellrc --group "PlasmaViews" --group "Panel 2" --group "Defaults" --key "thickness" 40
# Icon
kwriteconfig6 --file plasma-org.kde.plasma.desktop-appletsrc \
--group "Containments" --group "2" --group "Applets" --group "5" --group "Configuration" --group "General" \
--key "launchers" "applications:org.kde.konsole.desktop"
# Wallpaper

# Taskbar icon
kwriteconfig6 --file plasma-org.kde.plasma.desktop-appletsrc --group "Containments" --group "2" --group "Applets" \
--group "3" --group "Configuration" --group "General" \
--key "icon"  "/usr/share/pixmaps/kaes-logo.png"
EOF